name: CI
on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - 'demo/**'
      - '!**.md'
      - '!.changeset/**'
env:
  CI: true
jobs:
  check:
    name: format, lint, and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2.4.1

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Check lint
        run: pnpm run lint

      - name: Check pretty
        run: pnpm run pretty:check

  build_packages:
    name: Build packages
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2.4.1

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Setup build cache
        uses: actions/cache@v3
        id: build-packages-cache
        with:
          path: packages/**/dist
          key: ${{ runner.os }}-build-${{ hashFiles('packages/') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build
        if: steps.build-packages-cache.outputs.cache-hit != 'true'
        run: pnpm run build

  build_demo:
    name: Build demo
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2.4.1

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Setup build cache
        uses: actions/cache@v3
        id: build-demo-cache
        with:
          path: demo/dist
          key: ${{ runner.os }}-build-${{ hashFiles('demo/') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build
        if: steps.build-demo-cache.outputs.cache-hit != 'true'
        run: yarn run demo:build
