on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/demo.yml'
      - 'package.json'
      - 'yarn.lock'
      - 'demo/**'
      - '!**.md'
      - '!.changeset/**'

jobs:
  deploy:
    name: Deploy demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2.2.2

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Setup build cache
        uses: actions/cache@v3
        id: build-demo-cache
        with:
          path: demo/dist
          key: ${{ runner.os }}-build-${{ hashFiles('demo/') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build
        run: pnpm run demo:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: gh-pages
          folder: demo/dist
